services:
  processor-service:
    image: himal77/processor-service:latest
    container_name: processor-service
    ports:
      - "${PROCESSOR_SERVICE_PORT}:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: test
    env_file:
      - ../env/.env.test
    networks:
      - iot-net


  alert-service:
    image: himal77/alert-service:latest
    container_name: alert-service
    ports:
      - "${ALERT_SERVICE_PORT}:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: test
    env_file:
      - ../env/.env.test
    networks:
      - iot-net

  ingestor-service:
    image: himal77/ingestor-service:latest
    container_name: ingestor-service
    ports:
      - "${INGESTOR_SERVICE_PORT}:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: test
    env_file:
      - ../env/.env.test
    networks:
      - iot-net

  query-service:
    image: himal77/query-service:latest
    container_name: query-service
    ports:
      - "${QUERY_SERVICE_PORT}:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_PROFILES_ACTIVE: test
      SPRING_APPLICATION_NAME: query-service
    env_file:
      - ../env/.env.test
    networks:
      - iot-net

networks:
  iot-net:
    name: iot-net              # fixed name so every service can reference it
    external: true