services:
  ingestor-service:
    image: himal77/ingestor-service:latest
    container_name: ingestor-service
    ports:
      - "8081:8080"
    networks:
      - iot-net
      -
  processor-service:
    image: himal77/processor-service:latest
    container_name: processor-service
    ports:
      - "8082:8080"
    networks:
      - iot-net

  alert-service:
    image: himal77/alert-service:latest
    container_name: alert-service
    ports:
      - "8083:8080"
    networks:
      - iot-net

  query-service:
    image: himal77/query-service:latest
    container_name: query-service
    ports:
      - "8084:8080"
    networks:
      - iot-net

networks:
  iot-net:
    name: iot-net              # fixed name so every service can reference it
    external: true