# ingestor-service — I/O bound, HPA on CPU
# Scaled horizontally because it handles high-volume device data ingestion
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor-service
  namespace: iot
  labels:
    app: ingestor-service
spec:
  replicas: 2                    # Start with 2, HPA will scale up to 10
  selector:
    matchLabels:
      app: ingestor-service
  template:
    metadata:
      labels:
        app: ingestor-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: ingestor-service
          image: himal77/ingestor-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: iot-shared-config
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              cpu: "250m"        # HPA uses this as the baseline for % calculation
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: ingestor-service
  namespace: iot
spec:
  selector:
    app: ingestor-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
