# processor-service — CPU bound, HPA on CPU
# Higher CPU limits than ingestor since it does actual data processing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-service
  namespace: iot
  labels:
    app: processor-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor-service
  template:
    metadata:
      labels:
        app: processor-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: processor-service
          image: himal77/processor-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: iot-shared-config
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              cpu: "500m"        # Higher request — CPU bound workload
              memory: "256Mi"
            limits:
              cpu: "2"           # Allow bursting to 2 cores during heavy processing
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: iot
spec:
  selector:
    app: processor-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
