global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "processor-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8082']
    relabel_configs:
      - target_label: application
        replacement: processor-service

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]