global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    project: iot
    env: ${ENV}

scrape_configs:

  - job_name: "ingestor-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['${INGESTOR_HOST}:${INGESTOR_PORT}']
    relabel_configs:
      - target_label: application
        replacement: ingestor-service

  - job_name: "processor-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['${PROCESSOR_HOST}:${PROCESSOR_PORT}']
    relabel_configs:
      - target_label: application
        replacement: processor-service

  - job_name: "alert-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['${ALERT_HOST}:${ALERT_PORT}']
    relabel_configs:
      - target_label: application
        replacement: alert-service

  - job_name: "query-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['${QUERY_HOST}:${QUERY_PORT}']
    relabel_configs:
      - target_label: application
        replacement: query-service

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]