apiVersion: v1
kind: Service
metadata:
  name: locust-master-external
spec:
  type: NodePort
  selector:
    app: locust
    role: master
  ports:
    - name: web-ui
      port: 8089
      targetPort: 8089
      nodePort: 30089
