{
 "title": "Kubernetes Deployment Pods &&Springboot",
 "description": "Kubernetes Deployment Pods &&Springboot",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "origin_prometheus",
    "query": {
     "query": "label_values(kube_node_info,origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", origin_prometheus=~\"$origin_prometheus\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(sum(last_over_time(kube_pod_container_info{namespace=~\"$namespace\", container=~\"$container\", origin_prometheus=~\"$origin_prometheus\"}[$__range])) by (pod,namespace,container))"
    }
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": {
     "query": "label_values(hikaricp_connections_active{container=\"$container\", namespace=~\"$namespace\"},pool)"
    }
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC Connection Name",
    "query": {
     "query": "label_values(jdbc_connections_min{container=~\"$container\", namespace=~\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Info:[$pod]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "工作副本数量统计",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$container\",namespace=\"$namespace\"})",
     "legendFormat": "Pod Num"
    },
    {
     "expr": "max(kube_deployment_status_replicas_ready{deployment=\"$container\",namespace=\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_deployment_status_replicas_ready{deployment=\"$container\",namespace=\"$namespace\"}) / max(kube_deployment_spec_replicas{deployment=\"$container\",namespace=\"$namespace\"})",
     "legendFormat": "Ready Percent"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"$container\"}/kube_deployment_spec_replicas{namespace=\"$namespace\",deployment=~\"$container\"}",
     "legendFormat": "$container"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_service_info{namespace=\"$namespace\",service=~\"$container\"}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since deployment created.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{namespace=\"$namespace\",deployment=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"}) by (created_by_name, uid, pod, pod_ip, node,host_ip),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (pod,uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid,pod, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid,pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid,pod, container)) by (uid,pod)"
    },
    {
     "expr": "round(sum by (container,uid,pod)(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "xxj"
    },
    {
     "expr": "sum by(container,uid,pod)(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=~\"$container\",namespace=\"$namespace\"} >0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (process_start_time_seconds{container=\"$container\",pod=~\"$pod\"}) *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ceil(sum by (pod)(increase(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"}[5m])))",
     "legendFormat": "Restart 5 Minutes: {{pod}}"
    },
    {
     "expr": "sum by (pod,container,namespace)(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "Restart Total: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Num",
   "type": "timeseries",
   "description": "微服务(容器名)Pod数",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by(container,namespace)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "HikariCP Statistics:[$pod]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    { "title": "HikariCP Connections", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 } },
    {
     "title": "Connections Time",
     "type": "timeseries",
     "description": "Aquire   Time:平均获取时间\n\nCreation Time:平均创建时间\n\nUsage    Time:平均使用时间",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(hikaricp_connections_usage_seconds_sum{pool=\"$hikaricp_pool_name\",pod=\"$pod\"}[4m]) / \nirate(hikaricp_connections_usage_seconds_count{pool=\"$hikaricp_pool_name\",pod=\"$pod\"}[4m])",
       "legendFormat": "Usage Time"
      },
      {
       "expr": "irate(hikaricp_connections_acquire_seconds_sum{pool=~\"$hikaricp_pool_name\",pod=~\"$pod\"}[5m]) / \nirate(hikaricp_connections_acquire_seconds_count{pool=~\"$hikaricp_pool_name\",pod=~\"$pod\"}[5m])",
       "legendFormat": "Aquire Time"
      },
      {
       "expr": "irate(hikaricp_connections_creation_seconds_sum{pool=~\"$hikaricp_pool_name\",pod=~\"$pod\"}[5m]) / \nirate(hikaricp_connections_creation_seconds_count{pool=~\"$hikaricp_pool_name\",pod=~\"$pod\"}[5m])",
       "legendFormat": "Creation Time"
      },
      {
       "expr": "hikaricp_connections_timeout_total{pool=~\"$hikaricp_pool_name\",pod=~\"$pod\"}",
       "legendFormat": "Timeout"
      }
     ]
    },
    {
     "title": "Connections Count",
     "type": "timeseries",
     "description": "active: the number of connections currently in use\n\nidle: the number of current idle connections\n\npending: the number of threads waiting for a connection",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{pool=~\"$hikaricp_pool_name\",container=\"$container\",pod=~\"$pod\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{pool=~\"$hikaricp_pool_name\",container=\"$container\",pod=~\"$pod\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{pool=~\"$hikaricp_pool_name\",container=\"$container\",pod=~\"$pod\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "hikaricp_connections{pool=~\"$hikaricp_pool_name\",container=\"$container\",pod=~\"$pod\"}",
       "legendFormat": " Total"
      }
     ]
    },
    {
     "title": "JDBC Connections",
     "type": "stat",
     "description": "Java Database Connectivity",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jdbc_connections_active{pod=\"$pod\",name=\"$jdbc_connection_name\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "jdbc_connections_max{pod=\"$pod\",name=\"$jdbc_connection_name\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jdbc_connections_min{pod=\"$pod\",name=\"$jdbc_connection_name\"}",
       "legendFormat": "Min"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Resource:[$pod]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota:[$pod]",
   "type": "table",
   "description": "Pod CPU资源明细",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace) / (sum(kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}/100000) by (container, pod,node,namespace)) "
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU核数使用"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"} * on (pod) group_left(node) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_created{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\"} * on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Pod容器CPU使用率",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (namespace, container,pod) (rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) ) /(sum by (namespace,container, pod) (kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\",resource=\"cpu\"}) ) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU core usage",
   "type": "timeseries",
   "description": "Pod容器CPU核使用",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU使用：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU限制：{{ container}}"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  { "title": "Memory Resource:[$pod]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "description": "WSS（Working Set Size）：WSS 是指在一定时间范围内实际被使用的内存大小。它表示当前进程实际正在使用的内存量，包括代码、数据以及被频繁访问的页面。WSS 可以帮助你了解应用程序实际需要的内存量，有助于调整资源分配以提高性能。\n\nRSS（Resident Set Size）：RSS 是指进程当前驻留在物理内存中的内存量。它包括进程使用的所有内存，包括代码、数据、堆栈等，但不包括被交换到磁盘的部分。RSS 可以帮助你了解进程当前实际占用的物理内存量，有助于监控和优化内存使用。",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container=~\"$container\",container !=\"\",container!=\"POD\",pod=~\"$pod\",node=~\"^$Node$\"}) by (container, pod,node,namespace) / sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container=~\"$container\",container !=\"\",container!=\"POD\",pod=~\"$pod\",node=~\"^$Node$\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)/ sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"} * on (pod) group_left(node) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_created{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\"} * on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "description": "所有pod Memory Request总和",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Pod Memory Info-[$pod]",
   "type": "timeseries",
   "description": "WSS（Working Set Size）：WSS 是指在一定时间范围内实际被使用的内存大小。它表示当前进程实际正在使用的内存量，包括代码、数据以及被频繁访问的页面。WSS 可以帮助你了解应用程序实际需要的内存量，有助于调整资源分配以提高性能。\n\nRSS（Resident Set Size）：RSS 是指进程当前驻留在物理内存中的内存量。它包括进程使用的所有内存，包括代码、数据、堆栈等，但不包括被交换到磁盘的部分。RSS 可以帮助你了解进程当前实际占用的物理内存量，有助于监控和优化内存使用。",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod)/ max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod)/ max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "所有pod Memory Limit总和",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Pod RSS Info-[$pod]",
   "type": "timeseries",
   "description": "RSS（Resident Set Size）：RSS 是指进程当前驻留在物理内存中的内存量。它包括进程使用的所有内存，包括代码、数据、堆栈等，但不包括被交换到磁盘的部分。RSS 可以帮助你了解进程当前实际占用的物理内存量，有助于监控和优化内存使用。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod WSS Info-[$pod]",
   "type": "timeseries",
   "description": "WSS（Working Set Size）：WSS 是指在一定时间范围内实际被使用的内存大小。它表示当前进程实际正在使用的内存量，包括代码、数据以及被频繁访问的页面。WSS 可以帮助你了解应用程序实际需要的内存量，有助于调整资源分配以提高性能。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container =~\"$container\",node=~\"^$Node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)) by(pod)",
     "legendFormat": "Pod内存限制：{{ pod}}"
    }
   ]
  },
  { "title": "JVM:[$pod]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  { "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 } },
  { "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 } },
  { "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 } },
  {
   "title": "Heap memory usage %",
   "type": "timeseries",
   "description": "堆内存使用%",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container,pod) (jvm_memory_used_bytes{pod=~\"$pod\", area=\"heap\"}) / sum by(container,pod) (jvm_memory_committed_bytes{pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Classes:[$pod]",
   "type": "timeseries",
   "description": "类加载",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "loaded-{{pod}}"
    },
    {
     "expr": "jvm_classes_unloaded_classes_total{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "unloaded-{{pod}}"
    }
   ]
  },
  {
   "title": "Thread pool:[$pod]",
   "type": "timeseries",
   "description": "pool_size：当前线程数\n\npool_max：最大线程数\n\nactive：活动线程数\n\nqueued：排队任务数\n\npool_core：核心线程数\n\ncompleted_tasks：已完成任务数\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "executor_pool_size_threads{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "pool_size-{{pod}}"
    },
    {
     "expr": "executor_active_threads{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "active-{{pod}}"
    },
    {
     "expr": "executor_queued_tasks{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "queued-{{pod}}"
    },
    {
     "expr": "executor_pool_core_threads{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "pool_core-{{pod}}"
    },
    {
     "expr": "executor_completed_tasks_total{container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "completed_tasks-{{pod}}"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 } },
  { "title": "Api Request:[$container]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "HTTP Req/s",
   "type": "timeseries",
   "description": "QPS（每秒请求数）是指单位时间内的请求次数，是一个衡量系统吞吐量的重要指标。\n应用服务的请求QPS指的是在单位时间内，应用服务处理的请求数量。",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$container\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[5m])>0) by (status)",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Req/s  TOP7",
   "type": "timeseries",
   "description": "QPS（每秒请求数）是指单位时间内的请求次数，是一个衡量系统吞吐量的重要指标。\n应用服务的请求QPS指的是在单位时间内，应用服务处理的请求数量。",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum by(uri, method,status) (rate(http_server_requests_seconds_count{container=\"$container\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[5m]))>0)",
     "legendFormat": "{{method}}: {{uri}}"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 } },
  {
   "title": "HTTP Code Req/s",
   "type": "timeseries",
   "description": "HTTP 状态码统计",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$container\",status=~\"5..\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[2m])>0)",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$container\",status=~\"4..\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[2m])>0)",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$container\",status=~\"3..\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[2m])>0)",
     "legendFormat": "3xx - Redirections"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$container\",status=~\"2..\",uri!=\"/ping\",uri!=\"/actuator/prometheus\"}[2m])>0)",
     "legendFormat": "2xx - Success"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 } },
  { "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 } },
  { "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 } },
  { "gridPos": { "h": 8, "w": 7, "x": 0, "y": 150 } },
  { "gridPos": { "h": 8, "w": 12, "x": 7, "y": 150 } },
  { "gridPos": { "h": 8, "w": 5, "x": 19, "y": 150 } },
  { "gridPos": { "h": 8, "w": 7, "x": 0, "y": 158 } },
  { "gridPos": { "h": 8, "w": 12, "x": 7, "y": 158 } },
  { "title": "Network & File System:[$pod]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() sum(container_sockets{namespace=\"$namespace\",container!=\"\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "description": "The number of network errors including receiving and transmitting.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() (sum(container_network_receive_errors_total{namespace=\"$namespace\"}) by (pod) + sum(container_network_transmit_errors_total{namespace=\"$namespace\"}) by (pod)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Socket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(container_sockets{namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File System Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "{{pod}}/(Write)"
    }
   ]
  },
  {
   "title": "File System Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() max(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=~\"$container\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "{{pod}}(Read)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container =~\"$container\"}) by(container) *8"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container =~\"$container\"}) by(container) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bandwidth By Pod",
   "type": "timeseries",
   "description": "Pod网络带宽",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "max(max(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "流入:{{ pod}}"
    },
    {
     "expr": "max(max(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$pod\",namespace=~\"$namespace\",container =~\"$container\"}) by(pod) *8",
     "legendFormat": "流出:{{ pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth By Container",
   "type": "timeseries",
   "description": "微服务(容器名)网络带宽 ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container =~\"$container\"}) by(container) *8",
     "legendFormat": "流入:{{ container }}"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$namespace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$namespace\",container =~\"$container\"}) by(container) *8",
     "legendFormat": "流出:{{ container }}"
    }
   ]
  },
  { "title": "Logback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 185 } }
 ]
}