spring.application.name=ingestor-service

server.port=8081
processor.url=${PROCESSOR_SERVICE_URL}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.atlas.metrics.export.enabled=false

