spring.application.name=ingestor-service

server.port=8081
processor.url=http://localhost:8082

ingestor.max-batch-size=50000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.atlas.metrics.export.enabled=false

