server.port=8081
spring.application.name=ingestor-service

# Processor service URL (overridden by K8s env var)
processor.url=http://localhost:8082

# Batch size limit
ingestor.max-batch-size=500

# Intentionally limited thread pool
# so CPU pressure is measurable by HPA
# Do not increase this ? it is a thesis variable
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=5

# Connection timeout to processor
# If processor is overloaded, ingestor fails fast
# rather than piling up threads indefinitely
spring.mvc.async.request-timeout=5000

# Actuator / Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.atlas.metrics.export.enabled=false


